---
- hosts: all
  gather_facts: false
  collections:
    - awx.awx
    - community.vmware

  tasks:
    - name: Gather cluster info from given datacenter
      community.vmware.vmware_cluster_info:
        datacenter: {{ vcenter_datacenter }}
      delegate_to: localhost
      register: cluster_info
